/*
 *  DO NOT EDIT - automatically generated by TortoiseSVN script
 *  based on template file version.h.wcr
 */

#ifndef _VERSION_H_
#define _VERSION_H_

#define MAJOR_VER "1.01"
#define MINOR_VER "114"
#define BUILD "2017/03/18 15:21:27"
#define MODFIED 0
#define REV_RANGE "105:113"
#define MIXED_REV 1
#define SVN_URL "file:///C:/SVNRepository/AVR/Multitherm/trunk"

#endif
